### PR TITLE
Update to use new format of V1 Events API

### PR DESCRIPTION
**Pull request by mattcarp12**

### CODE REVIEW

**Comment by mattcarp12** [comment]
This PR should be merged when https://github.com/blues/hub/pull/3370 is deployed to production

**Comment by mattcarp12** [comment]
@gwolffblues or @m-mcgowan Please review this PR and I'll merge it when we deploy the changes to the Event API.

**Comment by gwolffblues** [comment]
Awaiting response to question about API version number before submitting response to review

**Review by gwolffblues — APPROVED** [review]

**Comment by m-mcgowan** [comment]
I did take a look at this, but don't really have the context to evaluate fully. But on the surface LGTM. :-)

**Pull request merged**
